name: Build and deploy docker image

on:
  push:
    branches:
      - main

env:
    location: "westeurope"
    resourceGroup: 'azpoe-hecmonitor-test'
    storage: 'azpoehecmonitortest'
    functionApp: 'rahulfunctionappgithubaction'
    skuStorage: 'Standard_LRS'
    functionsVersion: '4'
    pythonVersion: '3.11'
    AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
    localsecret: ${{secrets.LOCAL_SETTINGS_JSON}}
jobs:
  build-to-deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
    steps:
      - name: 'check secret'
        if: ${{env.localsecret != ''}}
        run: |
          echo "${{env.localsecret}}" > func.json
          cat func.json
  
  
    

