name: Build and deploy docker image

on:
  push:
    branches:
      - main

jobs:
    build-to-deploy:
        runs-on: ubuntu-latest
        steps:

            - name: 'Checkout Repo'
              uses: actions/checkout@v4
            
            - name: Az login
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
                enable-AzPSSession: true

            - name: Listing Accounts
              run: |
                az account show